### ISSUE TITLE
[Bug] Android1.0 beta 版微信登录后闪退

### ISSUE THREAD

**Issue by cooguyan** [easychen/pushdeer#145]
**描述你遇到的Bug**
Android1.0 beta 版微信**登录后**闪退。尝试过卸载，清楚全部数据甚至重启手机依然闪退。

**重现**
1. 打开PushDeer
2. 点击Sign in with WeChat
3. 弹出微信确认登陆
4. 自动跳转回PushDeer
5. 闪退

**错误日志**
```
--------- beginning of crash
08-29 09:50:48.172 25945 25945 E AndroidRuntime: FATAL EXCEPTION: main
08-29 09:50:48.172 25945 25945 E AndroidRuntime: Process: com.pushdeer.os, PID: 25945
08-29 09:50:48.172 25945 25945 E AndroidRuntime: java.lang.NullPointerException
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:292)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:857)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.View.draw(View.java:23153)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21971)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21911)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21911)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21911)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21911)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21911)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4586)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4559)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:21911)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:542)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:625)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4853)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4559)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3652)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2379)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9359)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1137)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:920)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:834)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1119)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:210)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:299)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8274)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
08-29 09:50:48.172 25945 25945 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
08-29 09:51:27.669 26193 26193 E AndroidRuntime: FATAL EXCEPTION: main

```

**客户端请填写以下信息**

**环境和版本**
 - 系统:  Android 12
 - 版本： 官方版1.2
 - 模块：客户端
 - 版本号 1.0 beta

**手机或电脑的的详细信息**
 - Device: Redmi K30U
 - OS: MIUI 13.0.3 稳定版 (Android 12)

 
**其他说明**
alpha存在点击通知不跳转的bug,所以我才用beta,但是beta版又存在闪退问题 😢

**Comment by cooguyan** [comment]
**更新**
细节补充：我先安装使用的是最新的alpha版，然后使用最新的beta版覆盖安装才出现了这个问题。
现在就算卸载beta版装回alpha版（[pushdeer-alpha-6.apk](https://github.com/easychen/pushdeer/releases/download/android1.0alpha/pushdeer-alpha-6.apk)）也会闪退，现在两个版本在我手机上都不能使用了😢
