### ISSUE TITLE
ios登录显示错误信息500[Bug]

### ISSUE THREAD

**Issue by codehai** [easychen/pushdeer#186]
看了错误日志显示:

[2023-08-16 08:09:28] local.ERROR: Cannot handle token prior to 2023-08-16T08:09:58+0000 {"exception":"[object] (Firebase\\JWT\\B
eforeValidException(code: 0): Cannot handle token prior to 2023-08-16T08:09:58+0000 at /app/api/vendor/griffinledingham/php-apple
-signin/Vendor/JWT.php:131)                                                                                                      
[stacktrace]                                                                                                                     
#0 /app/api/vendor/griffinledingham/php-apple-signin/ASDecoder.php(46): AppleSignIn\\Vendor\\JWT::decode('eyJraWQiOiJXNld...', '-
----BEGIN PUBL...', Array)                                                                                                       
#1 /app/api/vendor/griffinledingham/php-apple-signin/ASDecoder.php(28): AppleSignIn\\ASDecoder::decodeIdentityToken('eyJraWQiOiJX
Nld...')                                                                                                                         
#2 /app/api/app/Http/Helpers.php(15): AppleSignIn\\ASDecoder::getAppleSignInPayload('eyJraWQiOiJXNld...')                        
#3 /app/api/app/Http/Controllers/PushDeerUserController.php(221): getUserDataFromIdentityToken('eyJraWQiOiJXNld...')

**Comment by codehai** [comment]
> 看看服务器时间，我的就是和本地时间差了5分钟导致

还真是的 可以了
